/********************************************************************************
** Form generated from reading UI file 'pport_dialog.ui'
**
** Created: Fri 17. Jun 14:54:11 2011
**      by: Qt User Interface Compiler version 4.7.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PPORT_DIALOG_H
#define UI_PPORT_DIALOG_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QDialog>
#include <QtGui/QGroupBox>
#include <QtGui/QHBoxLayout>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>
#include <QtGui/QRadioButton>
#include <QtGui/QSpacerItem>
#include <QtGui/QTabWidget>
#include <QtGui/QTextEdit>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_PPort_DialogClass
{
public:
    QWidget *layoutWidget;
    QHBoxLayout *hboxLayout;
    QSpacerItem *spacerItem;
    QPushButton *okButton;
    QPushButton *cancelButton;
    QTabWidget *tabWidget;
    QWidget *tab1;
    QGroupBox *groupBox;
    QTextEdit *txtBIOSSettings;
    QPushButton *btnReadBIOS;
    QGroupBox *groupBox_5;
    QLineEdit *txtATBaseAddress;
    QLabel *lblATBaseAddress;
    QPushButton *btnSetInputMode;
    QPushButton *btnSetOutputMode;
    QPushButton *btnGetMode;
    QRadioButton *rbBaseAddrinHex;
    QRadioButton *rbBaseAddrinDec;
    QGroupBox *groupBox_6;
    QGroupBox *groupBox_4;
    QCheckBox *chkControlPortB0;
    QCheckBox *chkControlPortB1;
    QCheckBox *chkControlPortB2;
    QCheckBox *chkControlPortB3;
    QCheckBox *chkControlPortB4;
    QLabel *lblATBaseAddress_4;
    QCheckBox *chkControlPortB5;
    QLineEdit *txtControlPortReadValue;
    QGroupBox *groupBox_2;
    QCheckBox *chkDataPortB0;
    QCheckBox *chkDataPortB1;
    QCheckBox *chkDataPortB2;
    QCheckBox *chkDataPortB3;
    QCheckBox *chkDataPortB4;
    QCheckBox *chkDataPortB5;
    QCheckBox *chkDataPortB6;
    QCheckBox *chkDataPortB7;
    QLineEdit *txtDataPortReadValue;
    QLabel *lblATBaseAddress_2;
    QGroupBox *groupBox_3;
    QCheckBox *chkStatusPortB3;
    QCheckBox *chkStatusPortB4;
    QCheckBox *chkStatusPortB5;
    QCheckBox *chkStatusPortB6;
    QCheckBox *chkStatusPortB7;
    QLabel *lblATBaseAddress_3;
    QLineEdit *txtStatusPortReadValue;
    QPushButton *btnWritePort;
    QPushButton *btnReadPort;
    QWidget *tab2;
    QGroupBox *gb_CaptureThread;
    QGroupBox *groupBox_8;
    QCheckBox *chkCaptureMaskB4;
    QCheckBox *chkCaptureMaskB2;
    QCheckBox *chkCaptureMaskB7;
    QCheckBox *chkCaptureMaskB5;
    QCheckBox *chkCaptureMaskB0;
    QCheckBox *chkCaptureMaskB3;
    QCheckBox *chkCaptureMaskB6;
    QCheckBox *chkCaptureMaskB1;
    QGroupBox *groupBox_9;
    QLineEdit *txtCBaseAddress;
    QRadioButton *rbBaseAddrinDec_C;
    QRadioButton *rbBaseAddrinHex_C;
    QGroupBox *groupBox_10;
    QLineEdit *txtLHDelay_C;
    QLabel *lblATBaseAddress_5;
    QLabel *lblATBaseAddress_6;
    QLineEdit *txtHLDelay_C;
    QGroupBox *groupBox_11;
    QRadioButton *rbDecMethodHigh_MVC1;
    QRadioButton *rbDecMethod_MVC0;
    QRadioButton *rbDecMethodLow_MVC2;
    QGroupBox *groupBox_12;
    QLineEdit *txtFeedBackTriggVal;
    QLabel *lblATBaseAddress_7;
    QLineEdit *txt_NrOfFeedBacks;
    QLabel *lblATBaseAddress_8;
    QLineEdit *txtFeedBackStarted;
    QLabel *lblATBaseAddress_9;
    QLineEdit *txtFeedBackStopped;
    QLabel *lblATBaseAddress_10;
    QPushButton *btnStartCaptureThread;
    QPushButton *btnStopCaptureThread;
    QRadioButton *rdb_CaptureThreadRunning;
    QWidget *tab;
    QGroupBox *gb_GenerateThread;
    QGroupBox *gb_GenOutMask;
    QCheckBox *chkGenerateMaskB4;
    QCheckBox *chkGenerateMaskB2;
    QCheckBox *chkGenerateMaskB7;
    QCheckBox *chkGenerateMaskB5;
    QCheckBox *chkGenerateMaskB0;
    QCheckBox *chkGenerateMaskB3;
    QCheckBox *chkGenerateMaskB6;
    QCheckBox *chkGenerateMaskB1;
    QGroupBox *groupBox_14;
    QLineEdit *txtGBaseAddress;
    QRadioButton *rbBaseAddrinDec_G;
    QRadioButton *rbBaseAddrinHex_G;
    QGroupBox *gb_GenPulseShape;
    QLineEdit *txtPulseActiveTime_G;
    QLabel *lblATBaseAddress_11;
    QLabel *lblATBaseAddress_12;
    QLineEdit *txtRepetitionTime_G;
    QGroupBox *groupBox_16;
    QRadioButton *rbGenMethod_Pulse;
    QRadioButton *rbGenMethod_Value;
    QRadioButton *rbGenMethod_Periodical;
    QGroupBox *groupBox_17;
    QLineEdit *txtFeedBackGenVal;
    QLabel *lblATBaseAddress_13;
    QLineEdit *txt_GenNrOfFeedBacks;
    QLabel *lblATBaseAddress_14;
    QLineEdit *txtGenFeedBackStarted;
    QLabel *lblATBaseAddress_15;
    QLineEdit *txtGenFeedBackStopped;
    QLabel *lblATBaseAddress_16;
    QGroupBox *gb_GenActVal;
    QCheckBox *chkGenerateActiveB4;
    QCheckBox *chkGenerateActiveB2;
    QCheckBox *chkGenerateActiveB7;
    QCheckBox *chkGenerateActiveB5;
    QCheckBox *chkGenerateActiveB0;
    QCheckBox *chkGenerateActiveB3;
    QCheckBox *chkGenerateActiveB6;
    QCheckBox *chkGenerateActiveB1;
    QGroupBox *gb_GenInActVal;
    QCheckBox *chkGenerateInActiveB4;
    QCheckBox *chkGenerateInActiveB2;
    QCheckBox *chkGenerateInActiveB7;
    QCheckBox *chkGenerateInActiveB5;
    QCheckBox *chkGenerateInActiveB0;
    QCheckBox *chkGenerateInActiveB3;
    QCheckBox *chkGenerateInActiveB6;
    QCheckBox *chkGenerateInActiveB1;
    QPushButton *btnStartGenerateThread;
    QPushButton *btnStopGenerateThread;
    QRadioButton *rdb_GenerateThreadRunning;

    void setupUi(QDialog *PPort_DialogClass)
    {
        if (PPort_DialogClass->objectName().isEmpty())
            PPort_DialogClass->setObjectName(QString::fromUtf8("PPort_DialogClass"));
        PPort_DialogClass->resize(565, 495);
        layoutWidget = new QWidget(PPort_DialogClass);
        layoutWidget->setObjectName(QString::fromUtf8("layoutWidget"));
        layoutWidget->setGeometry(QRect(340, 460, 221, 33));
        hboxLayout = new QHBoxLayout(layoutWidget);
#ifndef Q_OS_MAC
        hboxLayout->setSpacing(6);
#endif
        hboxLayout->setContentsMargins(0, 0, 0, 0);
        hboxLayout->setObjectName(QString::fromUtf8("hboxLayout"));
        hboxLayout->setContentsMargins(0, 0, 0, 0);
        spacerItem = new QSpacerItem(131, 31, QSizePolicy::Expanding, QSizePolicy::Minimum);

        hboxLayout->addItem(spacerItem);

        okButton = new QPushButton(layoutWidget);
        okButton->setObjectName(QString::fromUtf8("okButton"));

        hboxLayout->addWidget(okButton);

        cancelButton = new QPushButton(layoutWidget);
        cancelButton->setObjectName(QString::fromUtf8("cancelButton"));

        hboxLayout->addWidget(cancelButton);

        tabWidget = new QTabWidget(PPort_DialogClass);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(0, 0, 565, 451));
        tab1 = new QWidget();
        tab1->setObjectName(QString::fromUtf8("tab1"));
        groupBox = new QGroupBox(tab1);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(230, 10, 321, 151));
        txtBIOSSettings = new QTextEdit(groupBox);
        txtBIOSSettings->setObjectName(QString::fromUtf8("txtBIOSSettings"));
        txtBIOSSettings->setGeometry(QRect(20, 30, 281, 71));
        btnReadBIOS = new QPushButton(groupBox);
        btnReadBIOS->setObjectName(QString::fromUtf8("btnReadBIOS"));
        btnReadBIOS->setGeometry(QRect(230, 110, 75, 31));
        groupBox_5 = new QGroupBox(tab1);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(10, 10, 211, 151));
        txtATBaseAddress = new QLineEdit(groupBox_5);
        txtATBaseAddress->setObjectName(QString::fromUtf8("txtATBaseAddress"));
        txtATBaseAddress->setGeometry(QRect(90, 20, 51, 20));
        lblATBaseAddress = new QLabel(groupBox_5);
        lblATBaseAddress->setObjectName(QString::fromUtf8("lblATBaseAddress"));
        lblATBaseAddress->setGeometry(QRect(10, 20, 71, 16));
        btnSetInputMode = new QPushButton(groupBox_5);
        btnSetInputMode->setObjectName(QString::fromUtf8("btnSetInputMode"));
        btnSetInputMode->setGeometry(QRect(10, 50, 191, 31));
        btnSetOutputMode = new QPushButton(groupBox_5);
        btnSetOutputMode->setObjectName(QString::fromUtf8("btnSetOutputMode"));
        btnSetOutputMode->setGeometry(QRect(10, 80, 191, 31));
        btnGetMode = new QPushButton(groupBox_5);
        btnGetMode->setObjectName(QString::fromUtf8("btnGetMode"));
        btnGetMode->setGeometry(QRect(10, 110, 191, 31));
        rbBaseAddrinHex = new QRadioButton(groupBox_5);
        rbBaseAddrinHex->setObjectName(QString::fromUtf8("rbBaseAddrinHex"));
        rbBaseAddrinHex->setGeometry(QRect(150, 10, 51, 19));
        rbBaseAddrinHex->setChecked(true);
        rbBaseAddrinDec = new QRadioButton(groupBox_5);
        rbBaseAddrinDec->setObjectName(QString::fromUtf8("rbBaseAddrinDec"));
        rbBaseAddrinDec->setGeometry(QRect(150, 30, 51, 19));
        groupBox_6 = new QGroupBox(tab1);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(10, 160, 541, 261));
        groupBox_4 = new QGroupBox(groupBox_6);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(340, 20, 191, 171));
        chkControlPortB0 = new QCheckBox(groupBox_4);
        chkControlPortB0->setObjectName(QString::fromUtf8("chkControlPortB0"));
        chkControlPortB0->setGeometry(QRect(10, 20, 161, 18));
        QFont font;
        font.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font.setPointSize(8);
        font.setBold(false);
        font.setItalic(false);
        font.setUnderline(true);
        font.setWeight(50);
        font.setStrikeOut(false);
        chkControlPortB0->setFont(font);
        chkControlPortB1 = new QCheckBox(groupBox_4);
        chkControlPortB1->setObjectName(QString::fromUtf8("chkControlPortB1"));
        chkControlPortB1->setGeometry(QRect(10, 40, 161, 18));
        chkControlPortB1->setFont(font);
        chkControlPortB2 = new QCheckBox(groupBox_4);
        chkControlPortB2->setObjectName(QString::fromUtf8("chkControlPortB2"));
        chkControlPortB2->setGeometry(QRect(10, 60, 181, 18));
        QFont font1;
        font1.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font1.setPointSize(8);
        font1.setBold(true);
        font1.setItalic(false);
        font1.setUnderline(false);
        font1.setWeight(75);
        font1.setStrikeOut(false);
        chkControlPortB2->setFont(font1);
        chkControlPortB3 = new QCheckBox(groupBox_4);
        chkControlPortB3->setObjectName(QString::fromUtf8("chkControlPortB3"));
        chkControlPortB3->setGeometry(QRect(10, 80, 171, 18));
        chkControlPortB3->setFont(font);
        chkControlPortB4 = new QCheckBox(groupBox_4);
        chkControlPortB4->setObjectName(QString::fromUtf8("chkControlPortB4"));
        chkControlPortB4->setGeometry(QRect(10, 100, 161, 18));
        lblATBaseAddress_4 = new QLabel(groupBox_4);
        lblATBaseAddress_4->setObjectName(QString::fromUtf8("lblATBaseAddress_4"));
        lblATBaseAddress_4->setGeometry(QRect(10, 140, 71, 16));
        chkControlPortB5 = new QCheckBox(groupBox_4);
        chkControlPortB5->setObjectName(QString::fromUtf8("chkControlPortB5"));
        chkControlPortB5->setGeometry(QRect(10, 120, 161, 18));
        txtControlPortReadValue = new QLineEdit(groupBox_4);
        txtControlPortReadValue->setObjectName(QString::fromUtf8("txtControlPortReadValue"));
        txtControlPortReadValue->setEnabled(false);
        txtControlPortReadValue->setGeometry(QRect(90, 140, 41, 20));
        groupBox_2 = new QGroupBox(groupBox_6);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 20, 141, 221));
        chkDataPortB0 = new QCheckBox(groupBox_2);
        chkDataPortB0->setObjectName(QString::fromUtf8("chkDataPortB0"));
        chkDataPortB0->setGeometry(QRect(10, 20, 121, 18));
        chkDataPortB1 = new QCheckBox(groupBox_2);
        chkDataPortB1->setObjectName(QString::fromUtf8("chkDataPortB1"));
        chkDataPortB1->setGeometry(QRect(10, 40, 121, 18));
        chkDataPortB2 = new QCheckBox(groupBox_2);
        chkDataPortB2->setObjectName(QString::fromUtf8("chkDataPortB2"));
        chkDataPortB2->setGeometry(QRect(10, 60, 121, 18));
        chkDataPortB3 = new QCheckBox(groupBox_2);
        chkDataPortB3->setObjectName(QString::fromUtf8("chkDataPortB3"));
        chkDataPortB3->setGeometry(QRect(10, 80, 121, 18));
        chkDataPortB4 = new QCheckBox(groupBox_2);
        chkDataPortB4->setObjectName(QString::fromUtf8("chkDataPortB4"));
        chkDataPortB4->setGeometry(QRect(10, 100, 121, 18));
        chkDataPortB5 = new QCheckBox(groupBox_2);
        chkDataPortB5->setObjectName(QString::fromUtf8("chkDataPortB5"));
        chkDataPortB5->setGeometry(QRect(10, 120, 121, 18));
        chkDataPortB6 = new QCheckBox(groupBox_2);
        chkDataPortB6->setObjectName(QString::fromUtf8("chkDataPortB6"));
        chkDataPortB6->setGeometry(QRect(10, 140, 121, 18));
        chkDataPortB7 = new QCheckBox(groupBox_2);
        chkDataPortB7->setObjectName(QString::fromUtf8("chkDataPortB7"));
        chkDataPortB7->setGeometry(QRect(10, 160, 121, 18));
        txtDataPortReadValue = new QLineEdit(groupBox_2);
        txtDataPortReadValue->setObjectName(QString::fromUtf8("txtDataPortReadValue"));
        txtDataPortReadValue->setEnabled(false);
        txtDataPortReadValue->setGeometry(QRect(90, 190, 41, 20));
        lblATBaseAddress_2 = new QLabel(groupBox_2);
        lblATBaseAddress_2->setObjectName(QString::fromUtf8("lblATBaseAddress_2"));
        lblATBaseAddress_2->setGeometry(QRect(10, 190, 71, 16));
        groupBox_3 = new QGroupBox(groupBox_6);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(160, 20, 171, 151));
        chkStatusPortB3 = new QCheckBox(groupBox_3);
        chkStatusPortB3->setObjectName(QString::fromUtf8("chkStatusPortB3"));
        chkStatusPortB3->setGeometry(QRect(10, 20, 151, 18));
        chkStatusPortB4 = new QCheckBox(groupBox_3);
        chkStatusPortB4->setObjectName(QString::fromUtf8("chkStatusPortB4"));
        chkStatusPortB4->setGeometry(QRect(10, 40, 151, 18));
        chkStatusPortB5 = new QCheckBox(groupBox_3);
        chkStatusPortB5->setObjectName(QString::fromUtf8("chkStatusPortB5"));
        chkStatusPortB5->setGeometry(QRect(10, 60, 151, 18));
        chkStatusPortB5->setFont(font1);
        chkStatusPortB6 = new QCheckBox(groupBox_3);
        chkStatusPortB6->setObjectName(QString::fromUtf8("chkStatusPortB6"));
        chkStatusPortB6->setGeometry(QRect(10, 80, 151, 18));
        chkStatusPortB7 = new QCheckBox(groupBox_3);
        chkStatusPortB7->setObjectName(QString::fromUtf8("chkStatusPortB7"));
        chkStatusPortB7->setGeometry(QRect(10, 100, 151, 18));
        chkStatusPortB7->setFont(font);
        lblATBaseAddress_3 = new QLabel(groupBox_3);
        lblATBaseAddress_3->setObjectName(QString::fromUtf8("lblATBaseAddress_3"));
        lblATBaseAddress_3->setGeometry(QRect(10, 120, 71, 16));
        txtStatusPortReadValue = new QLineEdit(groupBox_3);
        txtStatusPortReadValue->setObjectName(QString::fromUtf8("txtStatusPortReadValue"));
        txtStatusPortReadValue->setEnabled(false);
        txtStatusPortReadValue->setGeometry(QRect(90, 120, 41, 20));
        btnWritePort = new QPushButton(groupBox_6);
        btnWritePort->setObjectName(QString::fromUtf8("btnWritePort"));
        btnWritePort->setGeometry(QRect(430, 220, 101, 31));
        btnReadPort = new QPushButton(groupBox_6);
        btnReadPort->setObjectName(QString::fromUtf8("btnReadPort"));
        btnReadPort->setGeometry(QRect(320, 220, 101, 31));
        tabWidget->addTab(tab1, QString());
        tab2 = new QWidget();
        tab2->setObjectName(QString::fromUtf8("tab2"));
        gb_CaptureThread = new QGroupBox(tab2);
        gb_CaptureThread->setObjectName(QString::fromUtf8("gb_CaptureThread"));
        gb_CaptureThread->setGeometry(QRect(10, 10, 541, 361));
        groupBox_8 = new QGroupBox(gb_CaptureThread);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(340, 20, 81, 211));
        chkCaptureMaskB4 = new QCheckBox(groupBox_8);
        chkCaptureMaskB4->setObjectName(QString::fromUtf8("chkCaptureMaskB4"));
        chkCaptureMaskB4->setGeometry(QRect(20, 110, 51, 19));
        chkCaptureMaskB2 = new QCheckBox(groupBox_8);
        chkCaptureMaskB2->setObjectName(QString::fromUtf8("chkCaptureMaskB2"));
        chkCaptureMaskB2->setGeometry(QRect(20, 70, 51, 19));
        chkCaptureMaskB7 = new QCheckBox(groupBox_8);
        chkCaptureMaskB7->setObjectName(QString::fromUtf8("chkCaptureMaskB7"));
        chkCaptureMaskB7->setGeometry(QRect(20, 170, 51, 19));
        chkCaptureMaskB5 = new QCheckBox(groupBox_8);
        chkCaptureMaskB5->setObjectName(QString::fromUtf8("chkCaptureMaskB5"));
        chkCaptureMaskB5->setGeometry(QRect(20, 130, 51, 19));
        chkCaptureMaskB0 = new QCheckBox(groupBox_8);
        chkCaptureMaskB0->setObjectName(QString::fromUtf8("chkCaptureMaskB0"));
        chkCaptureMaskB0->setGeometry(QRect(20, 30, 51, 19));
        chkCaptureMaskB3 = new QCheckBox(groupBox_8);
        chkCaptureMaskB3->setObjectName(QString::fromUtf8("chkCaptureMaskB3"));
        chkCaptureMaskB3->setGeometry(QRect(20, 90, 51, 19));
        chkCaptureMaskB6 = new QCheckBox(groupBox_8);
        chkCaptureMaskB6->setObjectName(QString::fromUtf8("chkCaptureMaskB6"));
        chkCaptureMaskB6->setGeometry(QRect(20, 150, 51, 19));
        chkCaptureMaskB1 = new QCheckBox(groupBox_8);
        chkCaptureMaskB1->setObjectName(QString::fromUtf8("chkCaptureMaskB1"));
        chkCaptureMaskB1->setGeometry(QRect(20, 50, 51, 19));
        groupBox_9 = new QGroupBox(gb_CaptureThread);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(10, 20, 120, 71));
        txtCBaseAddress = new QLineEdit(groupBox_9);
        txtCBaseAddress->setObjectName(QString::fromUtf8("txtCBaseAddress"));
        txtCBaseAddress->setGeometry(QRect(10, 30, 51, 20));
        rbBaseAddrinDec_C = new QRadioButton(groupBox_9);
        rbBaseAddrinDec_C->setObjectName(QString::fromUtf8("rbBaseAddrinDec_C"));
        rbBaseAddrinDec_C->setGeometry(QRect(70, 40, 51, 19));
        rbBaseAddrinHex_C = new QRadioButton(groupBox_9);
        rbBaseAddrinHex_C->setObjectName(QString::fromUtf8("rbBaseAddrinHex_C"));
        rbBaseAddrinHex_C->setGeometry(QRect(70, 20, 51, 19));
        rbBaseAddrinHex_C->setChecked(true);
        groupBox_10 = new QGroupBox(gb_CaptureThread);
        groupBox_10->setObjectName(QString::fromUtf8("groupBox_10"));
        groupBox_10->setGeometry(QRect(10, 100, 121, 131));
        txtLHDelay_C = new QLineEdit(groupBox_10);
        txtLHDelay_C->setObjectName(QString::fromUtf8("txtLHDelay_C"));
        txtLHDelay_C->setGeometry(QRect(10, 40, 101, 20));
        lblATBaseAddress_5 = new QLabel(groupBox_10);
        lblATBaseAddress_5->setObjectName(QString::fromUtf8("lblATBaseAddress_5"));
        lblATBaseAddress_5->setGeometry(QRect(10, 20, 111, 16));
        lblATBaseAddress_6 = new QLabel(groupBox_10);
        lblATBaseAddress_6->setObjectName(QString::fromUtf8("lblATBaseAddress_6"));
        lblATBaseAddress_6->setGeometry(QRect(10, 70, 111, 16));
        txtHLDelay_C = new QLineEdit(groupBox_10);
        txtHLDelay_C->setObjectName(QString::fromUtf8("txtHLDelay_C"));
        txtHLDelay_C->setGeometry(QRect(10, 90, 101, 20));
        groupBox_11 = new QGroupBox(gb_CaptureThread);
        groupBox_11->setObjectName(QString::fromUtf8("groupBox_11"));
        groupBox_11->setGeometry(QRect(140, 20, 191, 81));
        rbDecMethodHigh_MVC1 = new QRadioButton(groupBox_11);
        rbDecMethodHigh_MVC1->setObjectName(QString::fromUtf8("rbDecMethodHigh_MVC1"));
        rbDecMethodHigh_MVC1->setGeometry(QRect(10, 40, 171, 19));
        rbDecMethod_MVC0 = new QRadioButton(groupBox_11);
        rbDecMethod_MVC0->setObjectName(QString::fromUtf8("rbDecMethod_MVC0"));
        rbDecMethod_MVC0->setGeometry(QRect(10, 20, 171, 19));
        rbDecMethod_MVC0->setChecked(true);
        rbDecMethodLow_MVC2 = new QRadioButton(groupBox_11);
        rbDecMethodLow_MVC2->setObjectName(QString::fromUtf8("rbDecMethodLow_MVC2"));
        rbDecMethodLow_MVC2->setGeometry(QRect(10, 60, 171, 19));
        groupBox_12 = new QGroupBox(gb_CaptureThread);
        groupBox_12->setObjectName(QString::fromUtf8("groupBox_12"));
        groupBox_12->setGeometry(QRect(140, 110, 191, 121));
        txtFeedBackTriggVal = new QLineEdit(groupBox_12);
        txtFeedBackTriggVal->setObjectName(QString::fromUtf8("txtFeedBackTriggVal"));
        txtFeedBackTriggVal->setEnabled(false);
        txtFeedBackTriggVal->setGeometry(QRect(130, 20, 51, 20));
        lblATBaseAddress_7 = new QLabel(groupBox_12);
        lblATBaseAddress_7->setObjectName(QString::fromUtf8("lblATBaseAddress_7"));
        lblATBaseAddress_7->setGeometry(QRect(10, 20, 81, 16));
        txt_NrOfFeedBacks = new QLineEdit(groupBox_12);
        txt_NrOfFeedBacks->setObjectName(QString::fromUtf8("txt_NrOfFeedBacks"));
        txt_NrOfFeedBacks->setEnabled(false);
        txt_NrOfFeedBacks->setGeometry(QRect(130, 40, 51, 20));
        lblATBaseAddress_8 = new QLabel(groupBox_12);
        lblATBaseAddress_8->setObjectName(QString::fromUtf8("lblATBaseAddress_8"));
        lblATBaseAddress_8->setGeometry(QRect(10, 40, 81, 16));
        txtFeedBackStarted = new QLineEdit(groupBox_12);
        txtFeedBackStarted->setObjectName(QString::fromUtf8("txtFeedBackStarted"));
        txtFeedBackStarted->setEnabled(false);
        txtFeedBackStarted->setGeometry(QRect(70, 70, 111, 20));
        lblATBaseAddress_9 = new QLabel(groupBox_12);
        lblATBaseAddress_9->setObjectName(QString::fromUtf8("lblATBaseAddress_9"));
        lblATBaseAddress_9->setGeometry(QRect(10, 70, 61, 16));
        txtFeedBackStopped = new QLineEdit(groupBox_12);
        txtFeedBackStopped->setObjectName(QString::fromUtf8("txtFeedBackStopped"));
        txtFeedBackStopped->setEnabled(false);
        txtFeedBackStopped->setGeometry(QRect(70, 90, 111, 20));
        lblATBaseAddress_10 = new QLabel(groupBox_12);
        lblATBaseAddress_10->setObjectName(QString::fromUtf8("lblATBaseAddress_10"));
        lblATBaseAddress_10->setGeometry(QRect(10, 90, 61, 16));
        btnStartCaptureThread = new QPushButton(tab2);
        btnStartCaptureThread->setObjectName(QString::fromUtf8("btnStartCaptureThread"));
        btnStartCaptureThread->setGeometry(QRect(10, 380, 121, 31));
        btnStopCaptureThread = new QPushButton(tab2);
        btnStopCaptureThread->setObjectName(QString::fromUtf8("btnStopCaptureThread"));
        btnStopCaptureThread->setGeometry(QRect(140, 380, 121, 31));
        rdb_CaptureThreadRunning = new QRadioButton(tab2);
        rdb_CaptureThreadRunning->setObjectName(QString::fromUtf8("rdb_CaptureThreadRunning"));
        rdb_CaptureThreadRunning->setEnabled(false);
        rdb_CaptureThreadRunning->setGeometry(QRect(420, 380, 121, 20));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(255, 5, 9, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QBrush brush2(QColor(255, 255, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush2);
        QBrush brush3(QColor(64, 64, 64, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        QBrush brush4(QColor(10, 36, 106, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Highlight, brush4);
        palette.setBrush(QPalette::Active, QPalette::HighlightedText, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Highlight, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        QBrush brush5(QColor(255, 0, 4, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Highlight, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush2);
        rdb_CaptureThreadRunning->setPalette(palette);
        rdb_CaptureThreadRunning->setLayoutDirection(Qt::RightToLeft);
        tabWidget->addTab(tab2, QString());
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        gb_GenerateThread = new QGroupBox(tab);
        gb_GenerateThread->setObjectName(QString::fromUtf8("gb_GenerateThread"));
        gb_GenerateThread->setGeometry(QRect(10, 10, 541, 361));
        gb_GenOutMask = new QGroupBox(gb_GenerateThread);
        gb_GenOutMask->setObjectName(QString::fromUtf8("gb_GenOutMask"));
        gb_GenOutMask->setGeometry(QRect(140, 20, 81, 191));
        chkGenerateMaskB4 = new QCheckBox(gb_GenOutMask);
        chkGenerateMaskB4->setObjectName(QString::fromUtf8("chkGenerateMaskB4"));
        chkGenerateMaskB4->setGeometry(QRect(20, 100, 51, 19));
        chkGenerateMaskB4->setChecked(true);
        chkGenerateMaskB2 = new QCheckBox(gb_GenOutMask);
        chkGenerateMaskB2->setObjectName(QString::fromUtf8("chkGenerateMaskB2"));
        chkGenerateMaskB2->setGeometry(QRect(20, 60, 51, 19));
        chkGenerateMaskB2->setChecked(true);
        chkGenerateMaskB7 = new QCheckBox(gb_GenOutMask);
        chkGenerateMaskB7->setObjectName(QString::fromUtf8("chkGenerateMaskB7"));
        chkGenerateMaskB7->setGeometry(QRect(20, 160, 51, 19));
        chkGenerateMaskB7->setChecked(true);
        chkGenerateMaskB5 = new QCheckBox(gb_GenOutMask);
        chkGenerateMaskB5->setObjectName(QString::fromUtf8("chkGenerateMaskB5"));
        chkGenerateMaskB5->setGeometry(QRect(20, 120, 51, 19));
        chkGenerateMaskB5->setChecked(true);
        chkGenerateMaskB0 = new QCheckBox(gb_GenOutMask);
        chkGenerateMaskB0->setObjectName(QString::fromUtf8("chkGenerateMaskB0"));
        chkGenerateMaskB0->setGeometry(QRect(20, 20, 51, 19));
        chkGenerateMaskB0->setChecked(true);
        chkGenerateMaskB3 = new QCheckBox(gb_GenOutMask);
        chkGenerateMaskB3->setObjectName(QString::fromUtf8("chkGenerateMaskB3"));
        chkGenerateMaskB3->setGeometry(QRect(20, 80, 51, 19));
        chkGenerateMaskB3->setChecked(true);
        chkGenerateMaskB6 = new QCheckBox(gb_GenOutMask);
        chkGenerateMaskB6->setObjectName(QString::fromUtf8("chkGenerateMaskB6"));
        chkGenerateMaskB6->setGeometry(QRect(20, 140, 51, 19));
        chkGenerateMaskB6->setChecked(true);
        chkGenerateMaskB1 = new QCheckBox(gb_GenOutMask);
        chkGenerateMaskB1->setObjectName(QString::fromUtf8("chkGenerateMaskB1"));
        chkGenerateMaskB1->setGeometry(QRect(20, 40, 51, 19));
        chkGenerateMaskB1->setChecked(true);
        groupBox_14 = new QGroupBox(gb_GenerateThread);
        groupBox_14->setObjectName(QString::fromUtf8("groupBox_14"));
        groupBox_14->setGeometry(QRect(10, 20, 120, 71));
        txtGBaseAddress = new QLineEdit(groupBox_14);
        txtGBaseAddress->setObjectName(QString::fromUtf8("txtGBaseAddress"));
        txtGBaseAddress->setGeometry(QRect(10, 30, 51, 20));
        rbBaseAddrinDec_G = new QRadioButton(groupBox_14);
        rbBaseAddrinDec_G->setObjectName(QString::fromUtf8("rbBaseAddrinDec_G"));
        rbBaseAddrinDec_G->setGeometry(QRect(70, 40, 51, 19));
        rbBaseAddrinHex_G = new QRadioButton(groupBox_14);
        rbBaseAddrinHex_G->setObjectName(QString::fromUtf8("rbBaseAddrinHex_G"));
        rbBaseAddrinHex_G->setGeometry(QRect(70, 20, 51, 19));
        rbBaseAddrinHex_G->setChecked(true);
        gb_GenPulseShape = new QGroupBox(gb_GenerateThread);
        gb_GenPulseShape->setObjectName(QString::fromUtf8("gb_GenPulseShape"));
        gb_GenPulseShape->setGeometry(QRect(10, 210, 391, 51));
        txtPulseActiveTime_G = new QLineEdit(gb_GenPulseShape);
        txtPulseActiveTime_G->setObjectName(QString::fromUtf8("txtPulseActiveTime_G"));
        txtPulseActiveTime_G->setGeometry(QRect(100, 20, 61, 20));
        lblATBaseAddress_11 = new QLabel(gb_GenPulseShape);
        lblATBaseAddress_11->setObjectName(QString::fromUtf8("lblATBaseAddress_11"));
        lblATBaseAddress_11->setGeometry(QRect(10, 20, 91, 16));
        lblATBaseAddress_12 = new QLabel(gb_GenPulseShape);
        lblATBaseAddress_12->setObjectName(QString::fromUtf8("lblATBaseAddress_12"));
        lblATBaseAddress_12->setGeometry(QRect(200, 20, 101, 16));
        txtRepetitionTime_G = new QLineEdit(gb_GenPulseShape);
        txtRepetitionTime_G->setObjectName(QString::fromUtf8("txtRepetitionTime_G"));
        txtRepetitionTime_G->setGeometry(QRect(310, 20, 61, 20));
        groupBox_16 = new QGroupBox(gb_GenerateThread);
        groupBox_16->setObjectName(QString::fromUtf8("groupBox_16"));
        groupBox_16->setGeometry(QRect(10, 90, 121, 91));
        rbGenMethod_Pulse = new QRadioButton(groupBox_16);
        rbGenMethod_Pulse->setObjectName(QString::fromUtf8("rbGenMethod_Pulse"));
        rbGenMethod_Pulse->setGeometry(QRect(10, 40, 61, 19));
        rbGenMethod_Value = new QRadioButton(groupBox_16);
        rbGenMethod_Value->setObjectName(QString::fromUtf8("rbGenMethod_Value"));
        rbGenMethod_Value->setGeometry(QRect(10, 20, 61, 19));
        rbGenMethod_Value->setChecked(false);
        rbGenMethod_Periodical = new QRadioButton(groupBox_16);
        rbGenMethod_Periodical->setObjectName(QString::fromUtf8("rbGenMethod_Periodical"));
        rbGenMethod_Periodical->setGeometry(QRect(10, 60, 91, 19));
        rbGenMethod_Periodical->setChecked(true);
        groupBox_17 = new QGroupBox(gb_GenerateThread);
        groupBox_17->setObjectName(QString::fromUtf8("groupBox_17"));
        groupBox_17->setGeometry(QRect(10, 260, 391, 71));
        txtFeedBackGenVal = new QLineEdit(groupBox_17);
        txtFeedBackGenVal->setObjectName(QString::fromUtf8("txtFeedBackGenVal"));
        txtFeedBackGenVal->setEnabled(false);
        txtFeedBackGenVal->setGeometry(QRect(130, 20, 51, 20));
        lblATBaseAddress_13 = new QLabel(groupBox_17);
        lblATBaseAddress_13->setObjectName(QString::fromUtf8("lblATBaseAddress_13"));
        lblATBaseAddress_13->setGeometry(QRect(10, 20, 111, 16));
        txt_GenNrOfFeedBacks = new QLineEdit(groupBox_17);
        txt_GenNrOfFeedBacks->setObjectName(QString::fromUtf8("txt_GenNrOfFeedBacks"));
        txt_GenNrOfFeedBacks->setEnabled(false);
        txt_GenNrOfFeedBacks->setGeometry(QRect(130, 40, 51, 20));
        lblATBaseAddress_14 = new QLabel(groupBox_17);
        lblATBaseAddress_14->setObjectName(QString::fromUtf8("lblATBaseAddress_14"));
        lblATBaseAddress_14->setGeometry(QRect(10, 40, 81, 16));
        txtGenFeedBackStarted = new QLineEdit(groupBox_17);
        txtGenFeedBackStarted->setObjectName(QString::fromUtf8("txtGenFeedBackStarted"));
        txtGenFeedBackStarted->setEnabled(false);
        txtGenFeedBackStarted->setGeometry(QRect(270, 20, 111, 20));
        lblATBaseAddress_15 = new QLabel(groupBox_17);
        lblATBaseAddress_15->setObjectName(QString::fromUtf8("lblATBaseAddress_15"));
        lblATBaseAddress_15->setGeometry(QRect(200, 20, 61, 16));
        txtGenFeedBackStopped = new QLineEdit(groupBox_17);
        txtGenFeedBackStopped->setObjectName(QString::fromUtf8("txtGenFeedBackStopped"));
        txtGenFeedBackStopped->setEnabled(false);
        txtGenFeedBackStopped->setGeometry(QRect(270, 40, 111, 20));
        lblATBaseAddress_16 = new QLabel(groupBox_17);
        lblATBaseAddress_16->setObjectName(QString::fromUtf8("lblATBaseAddress_16"));
        lblATBaseAddress_16->setGeometry(QRect(200, 40, 61, 16));
        gb_GenActVal = new QGroupBox(gb_GenerateThread);
        gb_GenActVal->setObjectName(QString::fromUtf8("gb_GenActVal"));
        gb_GenActVal->setGeometry(QRect(230, 20, 81, 191));
        chkGenerateActiveB4 = new QCheckBox(gb_GenActVal);
        chkGenerateActiveB4->setObjectName(QString::fromUtf8("chkGenerateActiveB4"));
        chkGenerateActiveB4->setGeometry(QRect(20, 100, 51, 19));
        chkGenerateActiveB2 = new QCheckBox(gb_GenActVal);
        chkGenerateActiveB2->setObjectName(QString::fromUtf8("chkGenerateActiveB2"));
        chkGenerateActiveB2->setGeometry(QRect(20, 60, 51, 19));
        chkGenerateActiveB7 = new QCheckBox(gb_GenActVal);
        chkGenerateActiveB7->setObjectName(QString::fromUtf8("chkGenerateActiveB7"));
        chkGenerateActiveB7->setGeometry(QRect(20, 160, 51, 19));
        chkGenerateActiveB5 = new QCheckBox(gb_GenActVal);
        chkGenerateActiveB5->setObjectName(QString::fromUtf8("chkGenerateActiveB5"));
        chkGenerateActiveB5->setGeometry(QRect(20, 120, 51, 19));
        chkGenerateActiveB0 = new QCheckBox(gb_GenActVal);
        chkGenerateActiveB0->setObjectName(QString::fromUtf8("chkGenerateActiveB0"));
        chkGenerateActiveB0->setGeometry(QRect(20, 20, 51, 19));
        chkGenerateActiveB3 = new QCheckBox(gb_GenActVal);
        chkGenerateActiveB3->setObjectName(QString::fromUtf8("chkGenerateActiveB3"));
        chkGenerateActiveB3->setGeometry(QRect(20, 80, 51, 19));
        chkGenerateActiveB6 = new QCheckBox(gb_GenActVal);
        chkGenerateActiveB6->setObjectName(QString::fromUtf8("chkGenerateActiveB6"));
        chkGenerateActiveB6->setGeometry(QRect(20, 140, 51, 19));
        chkGenerateActiveB1 = new QCheckBox(gb_GenActVal);
        chkGenerateActiveB1->setObjectName(QString::fromUtf8("chkGenerateActiveB1"));
        chkGenerateActiveB1->setGeometry(QRect(20, 40, 51, 19));
        gb_GenInActVal = new QGroupBox(gb_GenerateThread);
        gb_GenInActVal->setObjectName(QString::fromUtf8("gb_GenInActVal"));
        gb_GenInActVal->setGeometry(QRect(320, 20, 81, 191));
        chkGenerateInActiveB4 = new QCheckBox(gb_GenInActVal);
        chkGenerateInActiveB4->setObjectName(QString::fromUtf8("chkGenerateInActiveB4"));
        chkGenerateInActiveB4->setGeometry(QRect(20, 100, 51, 19));
        chkGenerateInActiveB2 = new QCheckBox(gb_GenInActVal);
        chkGenerateInActiveB2->setObjectName(QString::fromUtf8("chkGenerateInActiveB2"));
        chkGenerateInActiveB2->setGeometry(QRect(20, 60, 51, 19));
        chkGenerateInActiveB7 = new QCheckBox(gb_GenInActVal);
        chkGenerateInActiveB7->setObjectName(QString::fromUtf8("chkGenerateInActiveB7"));
        chkGenerateInActiveB7->setGeometry(QRect(20, 160, 51, 19));
        chkGenerateInActiveB5 = new QCheckBox(gb_GenInActVal);
        chkGenerateInActiveB5->setObjectName(QString::fromUtf8("chkGenerateInActiveB5"));
        chkGenerateInActiveB5->setGeometry(QRect(20, 120, 51, 19));
        chkGenerateInActiveB0 = new QCheckBox(gb_GenInActVal);
        chkGenerateInActiveB0->setObjectName(QString::fromUtf8("chkGenerateInActiveB0"));
        chkGenerateInActiveB0->setGeometry(QRect(20, 20, 51, 19));
        chkGenerateInActiveB3 = new QCheckBox(gb_GenInActVal);
        chkGenerateInActiveB3->setObjectName(QString::fromUtf8("chkGenerateInActiveB3"));
        chkGenerateInActiveB3->setGeometry(QRect(20, 80, 51, 19));
        chkGenerateInActiveB6 = new QCheckBox(gb_GenInActVal);
        chkGenerateInActiveB6->setObjectName(QString::fromUtf8("chkGenerateInActiveB6"));
        chkGenerateInActiveB6->setGeometry(QRect(20, 140, 51, 19));
        chkGenerateInActiveB1 = new QCheckBox(gb_GenInActVal);
        chkGenerateInActiveB1->setObjectName(QString::fromUtf8("chkGenerateInActiveB1"));
        chkGenerateInActiveB1->setGeometry(QRect(20, 40, 51, 19));
        btnStartGenerateThread = new QPushButton(tab);
        btnStartGenerateThread->setObjectName(QString::fromUtf8("btnStartGenerateThread"));
        btnStartGenerateThread->setGeometry(QRect(10, 380, 121, 31));
        btnStopGenerateThread = new QPushButton(tab);
        btnStopGenerateThread->setObjectName(QString::fromUtf8("btnStopGenerateThread"));
        btnStopGenerateThread->setGeometry(QRect(140, 380, 121, 31));
        rdb_GenerateThreadRunning = new QRadioButton(tab);
        rdb_GenerateThreadRunning->setObjectName(QString::fromUtf8("rdb_GenerateThreadRunning"));
        rdb_GenerateThreadRunning->setEnabled(false);
        rdb_GenerateThreadRunning->setGeometry(QRect(420, 380, 121, 20));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Highlight, brush4);
        palette1.setBrush(QPalette::Active, QPalette::HighlightedText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Highlight, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Highlight, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush2);
        rdb_GenerateThreadRunning->setPalette(palette1);
        rdb_GenerateThreadRunning->setLayoutDirection(Qt::RightToLeft);
        tabWidget->addTab(tab, QString());

        retranslateUi(PPort_DialogClass);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(PPort_DialogClass);
    } // setupUi

    void retranslateUi(QDialog *PPort_DialogClass)
    {
        PPort_DialogClass->setWindowTitle(QApplication::translate("PPort_DialogClass", "PPort_Dialog", 0, QApplication::UnicodeUTF8));
        okButton->setText(QApplication::translate("PPort_DialogClass", "OK", 0, QApplication::UnicodeUTF8));
        cancelButton->setText(QApplication::translate("PPort_DialogClass", "Cancel", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QApplication::translate("PPort_DialogClass", "System BIOS settings", 0, QApplication::UnicodeUTF8));
        btnReadBIOS->setText(QApplication::translate("PPort_DialogClass", "Read BIOS", 0, QApplication::UnicodeUTF8));
        groupBox_5->setTitle(QApplication::translate("PPort_DialogClass", "Device Settings", 0, QApplication::UnicodeUTF8));
        txtATBaseAddress->setText(QApplication::translate("PPort_DialogClass", "0x378", 0, QApplication::UnicodeUTF8));
        lblATBaseAddress->setText(QApplication::translate("PPort_DialogClass", "Base Address:", 0, QApplication::UnicodeUTF8));
        btnSetInputMode->setText(QApplication::translate("PPort_DialogClass", "Set for Input Mode", 0, QApplication::UnicodeUTF8));
        btnSetOutputMode->setText(QApplication::translate("PPort_DialogClass", "Set for Output Mode", 0, QApplication::UnicodeUTF8));
        btnGetMode->setText(QApplication::translate("PPort_DialogClass", "Get current Mode", 0, QApplication::UnicodeUTF8));
        rbBaseAddrinHex->setText(QApplication::translate("PPort_DialogClass", "Hex", 0, QApplication::UnicodeUTF8));
        rbBaseAddrinDec->setText(QApplication::translate("PPort_DialogClass", "Dec", 0, QApplication::UnicodeUTF8));
        groupBox_6->setTitle(QApplication::translate("PPort_DialogClass", "Device Port Values", 0, QApplication::UnicodeUTF8));
        groupBox_4->setTitle(QApplication::translate("PPort_DialogClass", "Control port @ Base Address + 2", 0, QApplication::UnicodeUTF8));
        chkControlPortB0->setText(QApplication::translate("PPort_DialogClass", "Bit 0, pin 1, Strobe, I/O", 0, QApplication::UnicodeUTF8));
        chkControlPortB1->setText(QApplication::translate("PPort_DialogClass", "Bit 1, pin 14, Auto Feed, I/O", 0, QApplication::UnicodeUTF8));
        chkControlPortB2->setText(QApplication::translate("PPort_DialogClass", "Bit 2, pin 16, Init Printer, I/O", 0, QApplication::UnicodeUTF8));
        chkControlPortB3->setText(QApplication::translate("PPort_DialogClass", "Bit 3, pin 17, Select Input, I/O", 0, QApplication::UnicodeUTF8));
        chkControlPortB4->setText(QApplication::translate("PPort_DialogClass", "Bit 4, Interrupt enable", 0, QApplication::UnicodeUTF8));
        lblATBaseAddress_4->setText(QApplication::translate("PPort_DialogClass", "Decimal Value:", 0, QApplication::UnicodeUTF8));
        chkControlPortB5->setText(QApplication::translate("PPort_DialogClass", "Bit 5, Tristate outputs", 0, QApplication::UnicodeUTF8));
        txtControlPortReadValue->setText(QApplication::translate("PPort_DialogClass", "0", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("PPort_DialogClass", "Data port @ Base Address", 0, QApplication::UnicodeUTF8));
        chkDataPortB0->setText(QApplication::translate("PPort_DialogClass", "Bit 0, pin 2, D0, I/O", 0, QApplication::UnicodeUTF8));
        chkDataPortB1->setText(QApplication::translate("PPort_DialogClass", "Bit 1, pin 3, D1, I/O", 0, QApplication::UnicodeUTF8));
        chkDataPortB2->setText(QApplication::translate("PPort_DialogClass", "Bit 2, pin 4, D2, I/O", 0, QApplication::UnicodeUTF8));
        chkDataPortB3->setText(QApplication::translate("PPort_DialogClass", "Bit 3, pin 5, D3, I/O", 0, QApplication::UnicodeUTF8));
        chkDataPortB4->setText(QApplication::translate("PPort_DialogClass", "Bit 4, pin 6, D4, I/O", 0, QApplication::UnicodeUTF8));
        chkDataPortB5->setText(QApplication::translate("PPort_DialogClass", "Bit 5, pin 7, D5, I/O", 0, QApplication::UnicodeUTF8));
        chkDataPortB6->setText(QApplication::translate("PPort_DialogClass", "Bit 6, pin 8, D6, I/O", 0, QApplication::UnicodeUTF8));
        chkDataPortB7->setText(QApplication::translate("PPort_DialogClass", "Bit 7, pin 9, D7, I/O", 0, QApplication::UnicodeUTF8));
        txtDataPortReadValue->setText(QApplication::translate("PPort_DialogClass", "0", 0, QApplication::UnicodeUTF8));
        lblATBaseAddress_2->setText(QApplication::translate("PPort_DialogClass", "Decimal Value:", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("PPort_DialogClass", "Status port @ Base Address + 1", 0, QApplication::UnicodeUTF8));
        chkStatusPortB3->setText(QApplication::translate("PPort_DialogClass", "Bit 3, pin 15, Error, I", 0, QApplication::UnicodeUTF8));
        chkStatusPortB4->setText(QApplication::translate("PPort_DialogClass", "Bit 4, pin 13, Select, I", 0, QApplication::UnicodeUTF8));
        chkStatusPortB5->setText(QApplication::translate("PPort_DialogClass", "Bit 5, pin 12, Paper, I", 0, QApplication::UnicodeUTF8));
        chkStatusPortB6->setText(QApplication::translate("PPort_DialogClass", "Bit 6, pin 10, Ack, I", 0, QApplication::UnicodeUTF8));
        chkStatusPortB7->setText(QApplication::translate("PPort_DialogClass", "Bit 7, pin 11, Busy, I", 0, QApplication::UnicodeUTF8));
        lblATBaseAddress_3->setText(QApplication::translate("PPort_DialogClass", "Decimal Value:", 0, QApplication::UnicodeUTF8));
        txtStatusPortReadValue->setText(QApplication::translate("PPort_DialogClass", "0", 0, QApplication::UnicodeUTF8));
        btnWritePort->setText(QApplication::translate("PPort_DialogClass", "Write Port Values", 0, QApplication::UnicodeUTF8));
        btnReadPort->setText(QApplication::translate("PPort_DialogClass", "Read Port Values", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab1), QApplication::translate("PPort_DialogClass", "Analyse and Test", 0, QApplication::UnicodeUTF8));
        gb_CaptureThread->setTitle(QApplication::translate("PPort_DialogClass", "Capture Settings", 0, QApplication::UnicodeUTF8));
        groupBox_8->setTitle(QApplication::translate("PPort_DialogClass", "Recieve Mask", 0, QApplication::UnicodeUTF8));
        chkCaptureMaskB4->setText(QApplication::translate("PPort_DialogClass", "Bit 4", 0, QApplication::UnicodeUTF8));
        chkCaptureMaskB2->setText(QApplication::translate("PPort_DialogClass", "Bit 2", 0, QApplication::UnicodeUTF8));
        chkCaptureMaskB7->setText(QApplication::translate("PPort_DialogClass", "Bit 7", 0, QApplication::UnicodeUTF8));
        chkCaptureMaskB5->setText(QApplication::translate("PPort_DialogClass", "Bit 5", 0, QApplication::UnicodeUTF8));
        chkCaptureMaskB0->setText(QApplication::translate("PPort_DialogClass", "Bit 0", 0, QApplication::UnicodeUTF8));
        chkCaptureMaskB3->setText(QApplication::translate("PPort_DialogClass", "Bit 3", 0, QApplication::UnicodeUTF8));
        chkCaptureMaskB6->setText(QApplication::translate("PPort_DialogClass", "Bit 6", 0, QApplication::UnicodeUTF8));
        chkCaptureMaskB1->setText(QApplication::translate("PPort_DialogClass", "Bit 1", 0, QApplication::UnicodeUTF8));
        groupBox_9->setTitle(QApplication::translate("PPort_DialogClass", "Base Address", 0, QApplication::UnicodeUTF8));
        txtCBaseAddress->setText(QApplication::translate("PPort_DialogClass", "0x378", 0, QApplication::UnicodeUTF8));
        rbBaseAddrinDec_C->setText(QApplication::translate("PPort_DialogClass", "Dec", 0, QApplication::UnicodeUTF8));
        rbBaseAddrinHex_C->setText(QApplication::translate("PPort_DialogClass", "Hex", 0, QApplication::UnicodeUTF8));
        groupBox_10->setTitle(QApplication::translate("PPort_DialogClass", "Post Timing Delay", 0, QApplication::UnicodeUTF8));
        txtLHDelay_C->setText(QApplication::translate("PPort_DialogClass", "0", 0, QApplication::UnicodeUTF8));
        lblATBaseAddress_5->setText(QApplication::translate("PPort_DialogClass", "After Low->High(ms):", 0, QApplication::UnicodeUTF8));
        lblATBaseAddress_6->setText(QApplication::translate("PPort_DialogClass", "After High->Low(ms):", 0, QApplication::UnicodeUTF8));
        txtHLDelay_C->setText(QApplication::translate("PPort_DialogClass", "0", 0, QApplication::UnicodeUTF8));
        groupBox_11->setTitle(QApplication::translate("PPort_DialogClass", "Detection Method", 0, QApplication::UnicodeUTF8));
        rbDecMethodHigh_MVC1->setText(QApplication::translate("PPort_DialogClass", "Masked Value Changed to High", 0, QApplication::UnicodeUTF8));
        rbDecMethod_MVC0->setText(QApplication::translate("PPort_DialogClass", "Masked Value Changed", 0, QApplication::UnicodeUTF8));
        rbDecMethodLow_MVC2->setText(QApplication::translate("PPort_DialogClass", "Masked Value Changed to Low", 0, QApplication::UnicodeUTF8));
        groupBox_12->setTitle(QApplication::translate("PPort_DialogClass", "Feedback", 0, QApplication::UnicodeUTF8));
        lblATBaseAddress_7->setText(QApplication::translate("PPort_DialogClass", "Triggered Value:", 0, QApplication::UnicodeUTF8));
        txt_NrOfFeedBacks->setText(QApplication::translate("PPort_DialogClass", "0", 0, QApplication::UnicodeUTF8));
        lblATBaseAddress_8->setText(QApplication::translate("PPort_DialogClass", "Nr of Feedbacks:", 0, QApplication::UnicodeUTF8));
        lblATBaseAddress_9->setText(QApplication::translate("PPort_DialogClass", "Started at:", 0, QApplication::UnicodeUTF8));
        lblATBaseAddress_10->setText(QApplication::translate("PPort_DialogClass", "Stopped at:", 0, QApplication::UnicodeUTF8));
        btnStartCaptureThread->setText(QApplication::translate("PPort_DialogClass", "Start Capture Thread", 0, QApplication::UnicodeUTF8));
        btnStopCaptureThread->setText(QApplication::translate("PPort_DialogClass", "Stop Capture Thread", 0, QApplication::UnicodeUTF8));
        rdb_CaptureThreadRunning->setText(QApplication::translate("PPort_DialogClass", "Thread Is Running", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab2), QApplication::translate("PPort_DialogClass", "Capture", 0, QApplication::UnicodeUTF8));
        gb_GenerateThread->setTitle(QApplication::translate("PPort_DialogClass", "Generate Settings", 0, QApplication::UnicodeUTF8));
        gb_GenOutMask->setTitle(QApplication::translate("PPort_DialogClass", "Output Mask", 0, QApplication::UnicodeUTF8));
        chkGenerateMaskB4->setText(QApplication::translate("PPort_DialogClass", "Bit 4", 0, QApplication::UnicodeUTF8));
        chkGenerateMaskB2->setText(QApplication::translate("PPort_DialogClass", "Bit 2", 0, QApplication::UnicodeUTF8));
        chkGenerateMaskB7->setText(QApplication::translate("PPort_DialogClass", "Bit 7", 0, QApplication::UnicodeUTF8));
        chkGenerateMaskB5->setText(QApplication::translate("PPort_DialogClass", "Bit 5", 0, QApplication::UnicodeUTF8));
        chkGenerateMaskB0->setText(QApplication::translate("PPort_DialogClass", "Bit 0", 0, QApplication::UnicodeUTF8));
        chkGenerateMaskB3->setText(QApplication::translate("PPort_DialogClass", "Bit 3", 0, QApplication::UnicodeUTF8));
        chkGenerateMaskB6->setText(QApplication::translate("PPort_DialogClass", "Bit 6", 0, QApplication::UnicodeUTF8));
        chkGenerateMaskB1->setText(QApplication::translate("PPort_DialogClass", "Bit 1", 0, QApplication::UnicodeUTF8));
        groupBox_14->setTitle(QApplication::translate("PPort_DialogClass", "Base Address", 0, QApplication::UnicodeUTF8));
        txtGBaseAddress->setText(QApplication::translate("PPort_DialogClass", "0x378", 0, QApplication::UnicodeUTF8));
        rbBaseAddrinDec_G->setText(QApplication::translate("PPort_DialogClass", "Dec", 0, QApplication::UnicodeUTF8));
        rbBaseAddrinHex_G->setText(QApplication::translate("PPort_DialogClass", "Hex", 0, QApplication::UnicodeUTF8));
        gb_GenPulseShape->setTitle(QApplication::translate("PPort_DialogClass", "Pulse Shape", 0, QApplication::UnicodeUTF8));
        txtPulseActiveTime_G->setText(QApplication::translate("PPort_DialogClass", "10", 0, QApplication::UnicodeUTF8));
        lblATBaseAddress_11->setText(QApplication::translate("PPort_DialogClass", "Active Time(ms):", 0, QApplication::UnicodeUTF8));
        lblATBaseAddress_12->setText(QApplication::translate("PPort_DialogClass", "Repetition Time(ms):", 0, QApplication::UnicodeUTF8));
        txtRepetitionTime_G->setText(QApplication::translate("PPort_DialogClass", "2000", 0, QApplication::UnicodeUTF8));
        groupBox_16->setTitle(QApplication::translate("PPort_DialogClass", "Generation Method", 0, QApplication::UnicodeUTF8));
        rbGenMethod_Pulse->setText(QApplication::translate("PPort_DialogClass", "Pulse", 0, QApplication::UnicodeUTF8));
        rbGenMethod_Value->setText(QApplication::translate("PPort_DialogClass", "Value", 0, QApplication::UnicodeUTF8));
        rbGenMethod_Periodical->setText(QApplication::translate("PPort_DialogClass", "Periodical", 0, QApplication::UnicodeUTF8));
        groupBox_17->setTitle(QApplication::translate("PPort_DialogClass", "Feedback", 0, QApplication::UnicodeUTF8));
        lblATBaseAddress_13->setText(QApplication::translate("PPort_DialogClass", "Generated Port Value:", 0, QApplication::UnicodeUTF8));
        txt_GenNrOfFeedBacks->setText(QApplication::translate("PPort_DialogClass", "0", 0, QApplication::UnicodeUTF8));
        lblATBaseAddress_14->setText(QApplication::translate("PPort_DialogClass", "Nr of Feedbacks:", 0, QApplication::UnicodeUTF8));
        lblATBaseAddress_15->setText(QApplication::translate("PPort_DialogClass", "Started at:", 0, QApplication::UnicodeUTF8));
        lblATBaseAddress_16->setText(QApplication::translate("PPort_DialogClass", "Stopped at:", 0, QApplication::UnicodeUTF8));
        gb_GenActVal->setTitle(QApplication::translate("PPort_DialogClass", "Active Value", 0, QApplication::UnicodeUTF8));
        chkGenerateActiveB4->setText(QApplication::translate("PPort_DialogClass", "Bit 4", 0, QApplication::UnicodeUTF8));
        chkGenerateActiveB2->setText(QApplication::translate("PPort_DialogClass", "Bit 2", 0, QApplication::UnicodeUTF8));
        chkGenerateActiveB7->setText(QApplication::translate("PPort_DialogClass", "Bit 7", 0, QApplication::UnicodeUTF8));
        chkGenerateActiveB5->setText(QApplication::translate("PPort_DialogClass", "Bit 5", 0, QApplication::UnicodeUTF8));
        chkGenerateActiveB0->setText(QApplication::translate("PPort_DialogClass", "Bit 0", 0, QApplication::UnicodeUTF8));
        chkGenerateActiveB3->setText(QApplication::translate("PPort_DialogClass", "Bit 3", 0, QApplication::UnicodeUTF8));
        chkGenerateActiveB6->setText(QApplication::translate("PPort_DialogClass", "Bit 6", 0, QApplication::UnicodeUTF8));
        chkGenerateActiveB1->setText(QApplication::translate("PPort_DialogClass", "Bit 1", 0, QApplication::UnicodeUTF8));
        gb_GenInActVal->setTitle(QApplication::translate("PPort_DialogClass", "Inactive Value", 0, QApplication::UnicodeUTF8));
        chkGenerateInActiveB4->setText(QApplication::translate("PPort_DialogClass", "Bit 4", 0, QApplication::UnicodeUTF8));
        chkGenerateInActiveB2->setText(QApplication::translate("PPort_DialogClass", "Bit 2", 0, QApplication::UnicodeUTF8));
        chkGenerateInActiveB7->setText(QApplication::translate("PPort_DialogClass", "Bit 7", 0, QApplication::UnicodeUTF8));
        chkGenerateInActiveB5->setText(QApplication::translate("PPort_DialogClass", "Bit 5", 0, QApplication::UnicodeUTF8));
        chkGenerateInActiveB0->setText(QApplication::translate("PPort_DialogClass", "Bit 0", 0, QApplication::UnicodeUTF8));
        chkGenerateInActiveB3->setText(QApplication::translate("PPort_DialogClass", "Bit 3", 0, QApplication::UnicodeUTF8));
        chkGenerateInActiveB6->setText(QApplication::translate("PPort_DialogClass", "Bit 6", 0, QApplication::UnicodeUTF8));
        chkGenerateInActiveB1->setText(QApplication::translate("PPort_DialogClass", "Bit 1", 0, QApplication::UnicodeUTF8));
        btnStartGenerateThread->setText(QApplication::translate("PPort_DialogClass", "Start Generate Thread", 0, QApplication::UnicodeUTF8));
        btnStopGenerateThread->setText(QApplication::translate("PPort_DialogClass", "Stop Generate Thread", 0, QApplication::UnicodeUTF8));
        rdb_GenerateThreadRunning->setText(QApplication::translate("PPort_DialogClass", "Thread Is Running", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("PPort_DialogClass", "Generate", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class PPort_DialogClass: public Ui_PPort_DialogClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PPORT_DIALOG_H
