# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
# message("You are running qmake on a generated .pro file. This may not work!")

#message $$ParentDirectory
#message $$_PRO_FILE_PWD_
#message $$PWD
#message $(QTDIR)
#message $$QMAKE_HOST.version_string
#message $$QMAKE_HOST.arc
#message $$QMAKE_HOST.os


TEMPLATE = subdirs
SUBDIRS += StimulGL/StimulGL.pro \
    Plugins/ParallelPortDevice/parallelportplugin.pro \
    Plugins/Retinotopic_Mapping/Retinotopic_Mappingplugin.pro \
    Plugins/ExtensionPluginTemplate/_extensionname_plugin.pro
